### ISSUE TITLE
-Wm-yC flag in tutorial

### ISSUE THREAD

**Issue by MatthewViens** [LaroldsJubilantJunkyard/drawing-on-the-background-and-window#1]
Hey, thanks for the tutorial! Following the corresponding steps at https://laroldsjubilantjunkyard.com/tutorials/how-to-make-a-gameboy-game/background-and-window/ I was unable to get any tiles loaded into VRAM. Removing the -WM-yC flag solved the issue. I don't think it was your original intention to use it in the first make.bat example, as when you go on to the "Adding color to the background/window" section you state that the flag needs to be added at this point.

**Comment by LaroldsJubilantJunkyard** [comment]
Hey, thanks for the input. I'll double check that and make the edit.

**Comment by LaroldsJubilantJunkyard** [comment]
Okay, I adjusted the tutorial some. That flag is not added until the "adding color" section. Good find!
